### PR TITLE
Issue 2067

### PR DESCRIPTION
**Pull request by hathibelagal-dev**
Added coverage for issue #2067 

I'm not sure what the `test_suite_id` is. I'm using 2525 because I see a lot of tests mention it.

Only on Linux, Iris seems to have problems with the png file `Bookmarks.StarDialog.NEW_FOLDER_CREATED`. It looks like the image hasn't been cropped correctly. You can look at it [here](https://github.com/mozilla/iris/blob/master/iris/api/core/firefox_ui/images/linux/editBMPanel_newFolderCreated.png).

So I created a new file for the pattern inside the tests/bookmark/images/linux directory. The test now runs correctly.

### CODE REVIEW

**Comment by tracywalker** [comment]
I'll review this today.  Thanks for the contribution. :)

2525 is the correct test_suite_id for these bookmark tests. It will be different for other features. I'll try to remember to give you test suite id, if you work on other tests.

**Comment by tracywalker** [comment]
The test passes for me on Linux and Windows.  However, it's failing on OSX in the assert at lines 50, then line 55 and finally line 63. 

I am working on non-retina Mac.  It is possible these patterns that are failing to be found need an adjustment to the similarity to make them work on non-retina Mac.  Please investigate.

One PEP8 compliance note is to add another blank line right after the import statement.

**Comment by hathibelagal-dev** [comment]
Thanks for the feedback, @tracywalker . Unfortunately, I don't have access to a Mac. Is there any other way I can solve this?

Also, I picked all those patterns from the api/core/firefox-ui directory. Should we create a new issue that some of the pngs there need to be fixed?

**Comment by tracywalker** [comment]
Oh, if you have no access to a Mac, then it will be too difficult to debug and fix on your side.  Let me take another look at this later.  I should be able to fix it.  

Great job on your first Mozilla Iris test case.

**Comment by tracywalker** [comment]
I'm going to land this as is. There are a couple of OSX assets in the firefox-UI library that aren't quite right. This test is fine other than that.  Once this is landed, I'll file an issue to fix the patterns in firefox-UI.

**Comment by hathibelagal-dev** [comment]
Great! Thank you, @tracywalker .

**Pull request merged**
