### PR TITLE
Issue 2916 (Fix default_search_code_google test)

### PR DESCRIPTION
**Pull request by spronoza**
Added coverage for #2916, please review.

### CODE REVIEW

**Comment by spronoza** [comment]
Fix for #2861

**Comment by tracywalker** [comment]
This patch does nothing to address the mismatch of the search code url as reported in issue #2916.  I expect this will still fail on the Linux machine that the issue was originally reported against.  Unfortunately, I cannot reproduce the reported issue on my local machine.

**Comment by spronoza** [comment]
We think that the copy_to_clipboard() action execute before the "&q=test" is adding to "https://www.google.com/webhp?client=firefox-b-1-d " in location bar. And extra check will prevent that issue

**Comment by tracywalker** [comment]
> We think that the copy_to_clipboard() action execute before the "&q=test" is adding to "https://www.google.com/webhp?client=firefox-b-1-d " in location bar. And extra check will prevent that issue

Wait,  there are two different urls not just one and then the same with appended "&q=test"
compare:
https://www.google.com/webhp?client=firefox-b-1-d  (wrong url with correct search code)
https://www.google.com/search?client=firefox-b-1-d&q=test (correct url and search code)

why is the webhp? version being served on your machine(s)?  
does adding checks for a google pattern really change that?

**Comment by tracywalker** [comment]
In no way will searching for google logo pattern guarantee that the results url is correct.  It may somehow improve things on your machines. But that is only coincidental.  If you want to be sure search? is in the url instead of webhp?, then you have to look for 'search?' with wait() explicitly

**Comment by tracywalker** [comment]
Why did you reduce the timeout lengths and swap paste() with type()? Some machines are slow and require the longer timeouts and paste() is much more reliable than type() when you just need to get a string into a text field.  You've made this test less stable on slower machines.

**Comment by tracywalker** [comment]
Please change this test case back to the way it was. 

The only thing that should be changed is making sure we properly enter the search query term before trigger a search.

**Comment by spronoza** [comment]
We did not reduce timeouts TINY_FIREFOX_TIMEOUT longer than DEFAULT_UI_DELAY_LONG.

**Comment by spronoza** [comment]
We did not reduced timeout, TINY_FIREFOX_TIMEOUT is longer than DEFAULT_UI_DELAY_LONG. Also we found out that the failures might be caused by some problem in the paste() function. You can check it by pressing Enter button in search bar. That action proceed you to the "https://www.google.com/webhp?client=firefox-b-1-d" instead "https://www.google.com/search?client=firefox-b-1-d&q=test" when text is pasted. 
Sorry that didn't mentioned it earlier

**Comment by tracywalker** [comment]
Sorry about the timeout, I didn't realize TINY_FIREFOX_TIMEOUT is longer than DEFAULT_UI_DELAY_LONG.

However  triggering the search with an empty string will result in the webhp? version of the UR.  None of this test is about testing an empty search string.  As the test is now,  it will falsely report as a PASS, if this empty query url is encountered.  Our tests need to ensure the search string is entered correctly before triggering the search. Then the test should be checking the entire url with assert_equal() just as the test was originally written.

**Comment by tracywalker** [comment]
The problem  probably isn't in paste() itself.  The problem is likely that the paste() function is occurring before the target text field has focus.

**Comment by spronoza** [comment]
Yeah, you right about assert_equal(). We will turn it back.
But about the paste() I almost sure that the problem not in focusing. Because if you not focused in the search field pressing Enter button will not redirect you to the "https://www.google.com/webhp?client=firefox-b-1-d"

**Comment by tracywalker** [comment]
Please return to using paste() and add a short timeout after each paste() function.

**Pull request merged**
