### PR TITLE
Issue 2312

### PR DESCRIPTION
**Pull request by dbakaev**
Added fix for #2312, please review.

### CODE REVIEW

**Comment by pavelciapa** [comment]
Closing as non actual. Test case already in dev -> 'basic_browser_use_with_antivirus '

**Comment by tracywalker** [comment]
I only renamed the test.  This test is still failing.   Please resolve conflicts (in test name)  and resubmit for review.

**Comment by tracywalker** [comment]
sorry, misread... this is being addressed om a new issue.

**Comment by pavelciapa** [comment]
> 
> 
> sorry, misread... this is being addressed om a new issue.

Yeap, right here -> #2680

**Pull request closed without merging**
