### PR TITLE
[Issue 1530] Improve OCR support in Iris 1.0

### PR DESCRIPTION
**Pull request by AndreiH**
this is for issue: https://github.com/mozilla/iris/issues/1530

More improvements to be done in the future.

### CODE REVIEW

**Comment by mwobensmith** [comment]
I sent you a private message regarding the issues with this on Retina Mac. Once we get it working there, this looks good.

A few small changes:
* Remove the `print` statements from the `create_region.py` test case, and replace them with logging messages.
* In `ocr_search.py`:
    * Remove commented lines 167, 230
    * Try to make comments a little more descriptive, and when possible, make them full sentences that end in periods.

Once that's done, and this works on all platforms, this is approved. Ask @silviuFlorin to land. 👍🏼

**Comment by AndreiH** [comment]
@mwobensmith I have also updated the PR according to the reviews ! Thanks !

**Comment by mwobensmith** [comment]
Looks great! 

* Still a few `print` statements in `create_region.py` that should be turned into logging messages - lines 58/62.

* For `Region.text()`, I see a few places in code where we name the `with_processing` argument, and others where we don't. I believe that this should always be a named argument, and that it should have a default value.

Make the above changes and have @silviuFlorin land it. Thank you!

By the way, I noticed that `create_region.py` did not pass for me, but that's because the lowercase letter `l` was mistaken for the pipe character `|`. This test is normally disabled, as it's an experiment, so it doesn't have to pass, but worth noting. When we have the ability to specify similarity, this issue should go away, I imagine.

**Comment by AndreiH** [comment]
Thank you for the review @mwobensmith !
That is true, `create_region.py` currently does not pass, because of the way we take the Region, with the cat and dog emoticons :). They also are converted to characters.
Of course I used this more for testing tesseract, being an experiment test I did not removed it from `Skipped` and I guess it's not useful to have it active in our Test Suite.
This test will be used next in our iris2 tests, where we will try to find a better wait to take the Regions.

Thanks !

**Pull request merged**
