### PR TITLE
Issue 1616

### PR DESCRIPTION
**Pull request by dbakaev**
Added coverage for #1616, please review.

### CODE REVIEW

**Comment by tracywalker** [comment]
Please resolve the conflicts so that this may be landed.

**Comment by dbakaev** [comment]
@tracywalker for the moment branch has no conflicts with the base branch

**Comment by tracywalker** [comment]
The PR here still shows conflicts for 'Rebase and merge.' If you don't mind 'Squash and merge,' then it's good to go.

**Comment by dbakaev** [comment]
@tracywalker This is strange, because I don't see any conflicts so far:
Screen Shot 2019-04-03 at 5 43 19 PM

**Comment by tracywalker** [comment]
We have been using 'Rebase and Merge' to preserve history/ownership.

**Pull request merged**
