### PR TITLE
Added coverage for issue 545

### PR DESCRIPTION
**Pull request by paulprokhorovmoz**
Added coverage for issue #545 , please review.

### CODE REVIEW

**Comment by paulprokhorovmoz** [comment]
I decided to add stack trace to console to give expressive info of failure reasons, it really helps when you try to investigate what actually failed in the test. Examples of such console messages:
error_log_sample
fail_test_sample

**Comment by paulprokhorovmoz** [comment]
> What happens if we get an error in our target code, and it happens to be in a function that contains the word "pytest"?

According to my code it will be skipped, so maybe it's better not to remove any items from stack trace. I'll remove filtering.

**Comment by mwobensmith** [comment]
What is the main problem that this code is trying to solve? Is it that the stack trace is too long? We could limit it to the last 5-10 lines if that would help.

**Comment by tracywalker** [comment]
As Paul has proposed, it would be quite helpful to have the test error/failure dumped to console during the test run.

**Comment by paulprokhorovmoz** [comment]
@mwobensmith Initial issue was about missing last trace back stack item because of 
`tb = call.excinfo.traceback.pop()` expression, which causes not full `call.excinfo.traceback` in `assert_object`. All other stuff is just my suggestion.

**Comment by paulprokhorovmoz** [comment]
@mwobensmith Filtering removed, please check

**Comment by paulprokhorovmoz** [comment]
I increased number of stack messages printed to console to 5, this number should be enough to locate the initial point of failure.
 
> My recommendation would be to print all of this information using logger.debug, but you expressed a different opinion. Can you tell me why?

In the DEBUG level you usually have a lot of info, you may not need it all to examine test failure reason. Moreover, in my opinion it would be useful to get error messages in such format in usual run mode, because it gives you brief info about the failure, so you may not need to relaunch test in the DEBUG mode.

**Comment by tracywalker** [comment]
I would like to see, on test failure, the name of the test that failed, the helper error message or the test case assert message.  So we don't pollute INFO and aren't forced to suffer through DEBUG spew, If this can be done at a -i WARNING level, that would be perfect.

**Comment by mwobensmith** [comment]
@paulprokhorovmoz - what about something simple like this? Or do we need more info, such as the line number of the assert?

```
(iris) bash-3.2$ iris sample
Desired target: sample
Found target named Sample

--------------------------Test session sample started---------------------------

Iris settings:
target: sample, rerun: False, highlight: False, clear: False, directory: , email: False, level: 20, control: False, locale: en-US, mouse: 0.5, no_check: True, override: False, port: 2000, test: , workdir: /Users/mwobensmith/.iris, exclude: , resize: False, virtual_keyboard: False

Sample settings:
sample_first_argument: sample first argument, sample_second_argument: sample second argument, sample_third_argument: sample third argument

----------------------------------Test Report-----------------------------------
Application: Sample, Platform: osx
Passed: 1, Failed: 0, Skipped: 0, Errors 1  -- Total: 2 Total time: 00:00:00.236

The following tests did not pass:
test_1.py : Unable to find image test.png


--------------------------------------------------------------------------------


--------------------------Test session sample complete--------------------------
```

**Comment by paulprokhorovmoz** [comment]
@mwobensmith We definitely need line number of assert in case of failure, moreover, we need line number of error in auxiliary function, if something went wrong there.

**Comment by mwobensmith** [comment]
Printing the assert message and line number of the failing test itself is easy. Deciding whether to print the previous frame and its assert/line number is harder, because not all failed tests will have this. 

Your last example prints the last 5 stack frames. It sounds like you probably only need either 1 or 2 (as above). Also, considering that you may have a lot of errors in a run, you want to print them in a way that is clean and easy to look at. Can you propose one or more ways to accomplish this? The example I provided above doesn't meet your needs because you say you might want the assert info for the auxiliary function as well. In that case, how should it look?

**Comment by mwobensmith** [comment]
After talking to @paulprokhorovmoz we are going to close this PR for now and make some prototypes to explore different ways of accomplishing the same thing. We will then target a date after we land the code changes for the PyPI work.

**Pull request closed without merging**
