### PR TITLE
Issue 3013

### PR DESCRIPTION
**Pull request by pavelciapa**
Added coverage for #3013, please review.

### CODE REVIEW

**Comment by tracywalker** [comment]
Please explain why there are 'if statements' of the assert exists of top_sites_available so that the test will PASS no matter what?  The method you have implemented can report false PASS. Just because top_sites_available isn't true doesn't mean about:blank is loaded, as you report.  Please determine, directly if about:blank page is loaded or not..

**Comment by pavelciapa** [comment]
> 
> 
> Please explain why there are 'if statements' of the assert exists of top_sites_available so that the test will PASS no matter what? The method you have implemented can report false PASS. Just because top_sites_available isn't true doesn't mean about:blank is loaded, as you report. Please determine, directly if about:blank page is loaded or not..

When testing `'about:blank' `and `'about:newtab'` I encountered that tab icon and tab title are the same, and according to community answer that I received, there is no way to reveal URL in address bar -> https://support.mozilla.org/en-US/questions/1258640 or distinguish these two tabs via about:config options

But as I know there should be two new tabs after restart, so I click on inactive tab one after another. But now I agree that my approach is somehow tricky 

First I will assert image and then assert_false of pattern image.

**Comment by tracywalker** [comment]
Pavel, to check the URL bar contents,  select_location_bar() then copy the copy the contents to clipboard, assign that to a variable and finally assert the text sting matches expected text.  See example in lines 66-72 of https://github.com/mozilla/iris/blob/master/iris/tests/search/default_search_code_google.py

**Comment by pavelciapa** [comment]
> 
> 
> Pavel, to check the URL bar contents, select_location_bar() then copy the copy the contents to clipboard, assign that to a variable and finally assert the text sting matches expected text. See example in lines 66-72 of https://github.com/mozilla/iris/blob/master/iris/tests/search/default_search_code_google.py

as I explained above, community members gave me answer(https://support.mozilla.org/en-US/questions/1258640) that there is no way to reveal URL in URL bar for about:new_tab and about:blank pages.

**Pull request merged**
